import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {handleApi,type Bindings} from '../lib/urdesigner/server';
import {seal,unseal} from '../lib/urdesigner/vault';
import {freshDesign,applyProposal,normalizeDocument} from '../lib/urdesigner/model';
import {allowedEndpoint} from '../lib/urdesigner/providers';
import {callProvider} from '../lib/urdesigner/ai';
const alice={userId:'alice',displayName:'Alice',email:'alice@example.test'},bob={userId:'bob',displayName:'Bob',email:'bob@example.test'};
function setup(){const sqlite=new DatabaseSync(':memory:');for(const name of readdirSync('drizzle').filter(n=>n.endsWith('.sql')).sort())sqlite.exec(readFileSync('drizzle/'+name,'utf8'));const db:any={prepare(sql:string){const s=sqlite.prepare(sql);let params:any[]=[];return {bind(...v:any[]){params=v;return this},async first(){return s.get(...params)||null},async all(){return {results:s.all(...params)}},async run(){const r=s.run(...params);return {meta:{changes:Number(r.changes)}}}}},async batch(statements:any[]){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results}catch(e){sqlite.exec('ROLLBACK');throw e}}};const objects=new Map();const bucket:any={async put(key:string,value:any){objects.set(key,value)},async get(key:string){const value=objects.get(key);return value?{body:value}:null},async delete(key:string){objects.delete(key)}};return {sqlite,env:{DB:db,BUCKET:bucket,VAULT_KEY:Buffer.alloc(32,7).toString('base64'),ADMIN_EMAIL:alice.email} as Bindings}}
function request(path:string,method='GET',data?:unknown,origin='https://studio.test'){return new Request('https://studio.test/api/'+path,{method,headers:{Origin:origin,'X-URDesigner-Request':'1','Content-Type':'application/json'},body:data===undefined?undefined:JSON.stringify(data)})}
test('AES-GCM key round-trip, unique nonce and owner-bound authentication',async()=>{const key=Buffer.alloc(32,9).toString('base64'),a=await seal('provider-secret',key,'alice','id'),b=await seal('provider-secret',key,'alice','id');assert.notEqual(a,b);assert.equal(await unseal(a,key,'alice','id'),'provider-secret');await assert.rejects(unseal(a,key,'bob','id'));await assert.rejects(unseal(a,key,'alice','other'))});
test('unauthenticated and cross-origin writes rejected',async()=>{const {env}=setup();assert.equal((await handleApi(request('projects'),null,env)).status,401);assert.equal((await handleApi(request('projects/'+crypto.randomUUID(),'PUT',{document:freshDesign(),revision:0},'https://evil.test'),alice,env)).status,403)});
test('project ownership, save conflict and revision snapshots',async()=>{const {env,sqlite}=setup(),id=crypto.randomUUID(),d=freshDesign();assert.equal((await handleApi(request('projects/'+id,'PUT',{document:d,revision:0}),alice,env)).status,200);assert.equal((await handleApi(request('projects/'+id),bob,env)).status,404);assert.deepEqual(await (await handleApi(request('projects'),bob,env)).json(),[]);assert.equal((await handleApi(request('projects/'+id,'PUT',{document:d,revision:1}),bob,env)).status,409);assert.equal((await handleApi(request('projects/'+id,'PUT',{document:{...d,title:'Updated'},revision:1}),alice,env)).status,200);assert.equal((await handleApi(request('projects/'+id,'PUT',{document:d,revision:1}),alice,env)).status,409);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM revisions').get()?.n,1);assert.equal(((await (await handleApi(request('projects/'+id),alice,env)).json()) as any).document.title,'Updated');await handleApi(request('projects/'+id,'DELETE'),bob,env);assert.equal((await handleApi(request('projects/'+id),alice,env)).status,200)});
test('keys never appear in list responses and another owner cannot delete them',async()=>{const {env,sqlite}=setup(),id=crypto.randomUUID();sqlite.prepare('INSERT INTO connections VALUES (?,?,?,?,?,?,?)').run(id,'alice','openai','test',null,'super-secret-ciphertext',0);const response=await handleApi(request('connections'),alice,env),body=await response.text();assert.ok(!body.includes('ciphertext'));assert.ok(!body.includes('super-secret'));await handleApi(request('connections/'+id,'DELETE'),bob,env);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM connections').get()?.n,1);await handleApi(request('connections/'+id,'DELETE'),alice,env);assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM connections').get()?.n,0)});
test('custom endpoints disallow SSRF destinations unless explicitly approved',()=>{for(const url of ['http://localhost:11434/v1','https://127.0.0.1/v1','https://example.test/v1?key=secret','https://user:pass@example.test/v1'])assert.throws(()=>allowedEndpoint(url,'https://example.test/v1'));assert.equal(allowedEndpoint('https://example.test/v1','https://example.test/v1'),'https://example.test/v1')});
test('AI proposals allow only supported edits and preserve manual layers',()=>{const d=freshDesign(),next=applyProposal(d,{explanation:'Warm palette',changes:{color:'#996633',fabric:'linen'}});assert.equal(next.color,'#996633');assert.equal(d.color,'#c3b8a5');assert.deepEqual(next.layers,d.layers);assert.throws(()=>applyProposal(d,{explanation:'bad',changes:{script:'steal'}}));assert.throws(()=>normalizeDocument({...d,color:'javascript:bad'}));assert.throws(()=>normalizeDocument({...d,sleeve:Infinity}))});
test('provider adapter uses backend key and refuses redirects',async()=>{let options:any;const mock:any=async(_url:string,opt:any)=>{options=opt;return Response.json({choices:[{message:{content:'Connected'}}]})};assert.equal(await callProvider({provider:'groq',model:'test'},'secret',[{role:'user',content:'Hi'}],'System','',mock),'Connected');assert.equal(options.headers.Authorization,'Bearer secret');assert.equal(options.redirect,'manual');assert.equal(JSON.parse(options.body).max_tokens,1600)});
test('provider error bodies are never exposed',async()=>{const mock:any=async()=>new Response('sensitive echoed key',{status:401});await assert.rejects(callProvider({provider:'openai',model:'test'},'secret',[],'System','',mock),e=>e instanceof Error&&!e.message.includes('sensitive')&&e.message.includes('rejected'))});
test('administrator endpoint excludes other accounts',async()=>{const {env}=setup();assert.equal((await handleApi(request('admin'),bob,env)).status,403);assert.equal((await handleApi(request('admin'),alice,env)).status,200)});
test('asset access is owner scoped and foreign asset references fail',async()=>{const {env,sqlite}=setup(),asset=crypto.randomUUID();sqlite.prepare('INSERT INTO assets VALUES (?,?,?,?,?)').run(asset,'alice','logo',100,0);assert.equal((await handleApi(request('assets/'+asset),bob,env)).status,404);const d=freshDesign();d.layers=[{id:crypto.randomUUID(),type:'image',name:'logo',side:'front',x:0,y:0,scaleX:1,scaleY:1,angle:0,fill:'#000000',opacity:1,visible:true,locked:false,width:10,height:10,asset}];assert.equal((await handleApi(request('projects/'+crypto.randomUUID(),'PUT',{document:d,revision:0}),bob,env)).status,400)});
test('account checks never generate text and refuse redirects',async()=>{const {testProvider}=await import('../lib/urdesigner/ai');let request:any;const mock:any=async(url:string,options:any)=>{request={url,options};return Response.json({data:[]})};assert.equal(await testProvider({provider:'groq',model:'model'},'key','',mock),true);assert.ok(request.url.endsWith('/models'));assert.equal(request.options.body,undefined);assert.equal(request.options.redirect,'manual');const redirect:any=async()=>new Response(null,{status:302,headers:{Location:'https://untrusted.test'}});await assert.rejects(testProvider({provider:'openai',model:'model'},'secret','',redirect),/not forwarded/)});
test('all 27 garments validate and produce finite volumetric geometry',async()=>{const {garmentCatalog}=await import('../lib/urdesigner/catalog');const {selectGarment,contour}=await import('../lib/urdesigner/model');const {garmentSurface}=await import('../lib/urdesigner/mesh');assert.equal(garmentCatalog.length,27);const signatures=new Set();for(const spec of garmentCatalog){const d=selectGarment(freshDesign(),spec.id);normalizeDocument(d);signatures.add(JSON.stringify(contour(d)));const g=garmentSurface(d,'front');assert.ok(Array.from(g.getAttribute('position').array).every(Number.isFinite));g.computeBoundingBox();assert.ok(g.boundingBox!.max.z-g.boundingBox!.min.z>.1);g.dispose()}assert.ok(signatures.size>=24)});
test('old saved documents receive construction defaults',()=>{const d:any=freshDesign();delete d.construction;const recovered=normalizeDocument(d);assert.equal(recovered.construction.neckline,'round');assert.equal(recovered.construction.length,1)});

test('reference assets and historical documents remain owner-scoped',async()=>{const {env,sqlite}=setup(),asset=crypto.randomUUID(),id=crypto.randomUUID();sqlite.prepare('INSERT INTO assets VALUES (?,?,?,?,?)').run(asset,'alice','reference',100,0);const d={...freshDesign(),references:[{id:crypto.randomUUID(),asset,name:'Reference',note:'Private'}]};assert.equal((await handleApi(request('projects/'+id,'PUT',{document:d,revision:0}),bob,env)).status,400);assert.equal((await handleApi(request('projects/'+id,'PUT',{document:d,revision:0}),alice,env)).status,200);await handleApi(request('projects/'+id,'PUT',{document:{...d,title:'Changed'},revision:1}),alice,env);assert.deepEqual(await (await handleApi(request('history/'+id),bob,env)).json(),[]);assert.equal(((await (await handleApi(request('history/'+id),alice,env)).json()) as any[]).length,1)});
test('share links expose only snapshots and owner can revoke',async()=>{const {env}=setup(),project=crypto.randomUUID();await handleApi(request('projects/'+project,'PUT',{document:freshDesign(),revision:0}),alice,env);const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aDXsAAAAASUVORK5CYII=';const res=await handleApi(request('shares','POST',{project,title:'Public preview',front:png,back:png}),alice,env);assert.equal(res.status,200);const {id}=await res.json() as any;const shared=await handleApi(request('shared/'+id),null,env);assert.equal(shared.status,200);assert.deepEqual(Object.keys(await shared.json() as object).sort(),['back','front','title']);await handleApi(request('shares/'+id,'DELETE'),bob,env);assert.equal((await handleApi(request('shared/'+id),null,env)).status,200);await handleApi(request('shares/'+id,'DELETE'),alice,env);assert.equal((await handleApi(request('shared/'+id),null,env)).status,404)});
