import {assetURL} from './local-workspace';
import {Canvas,StaticCanvas,Rect,Circle,Textbox,Path,FabricImage,FabricObject} from 'fabric';
import {Design,Layer,Side,drawGarment,silhouettePath} from './model';
export async function layerObject(l:Layer){let o:FabricObject;const options={left:l.x,top:l.y,scaleX:Math.abs(l.scaleX),scaleY:Math.abs(l.scaleY),flipX:l.scaleX<0,flipY:l.scaleY<0,angle:l.angle,fill:l.fill,opacity:l.opacity,visible:l.visible,selectable:!l.locked,evented:!l.locked,cornerColor:'#c8a97e',borderColor:'#c8a97e',transparentCorners:false,cornerSize:9};
 if(l.type==='text')o=new Textbox(l.text||'',{width:l.width,fontSize:l.fontSize||26,fontFamily:l.fontFamily||'Arial',...options});else if(l.type==='circle')o=new Circle({radius:l.width/2,...options});else if(l.type==='path')o=new Path(l.path as any,{...options,fill:'',stroke:l.fill,strokeWidth:l.strokeWidth||4,strokeLineCap:'round',strokeLineJoin:'round'});else if(l.type==='image'){o=await FabricImage.fromURL(await assetURL(l.asset!));o.set({...options,width:l.width,height:l.height})}else o=new Rect({width:l.width,height:l.height,...options});(o as any).layerId=l.id;return o;
}
export function updateFromObject(l:Layer,o:FabricObject):Layer{return{...l,x:o.left,y:o.top,scaleX:o.scaleX*(o.flipX?-1:1),scaleY:o.scaleY*(o.flipY?-1:1),angle:o.angle,width:o.width,height:o.height,...(l.type==='text'?{text:(o as Textbox).text}:{})}}
export async function paint(canvas:Canvas|StaticCanvas,d:Design,side:Side){const background=document.createElement('canvas');background.width=512;background.height=640;drawGarment(background.getContext('2d')!,d,side);if(d.fabricImage){const image=await FabricImage.fromURL(await assetURL(d.fabricImage));const ctx=background.getContext('2d')!;ctx.save();ctx.clip(new Path2D(silhouettePath(d,side)));const tile=document.createElement('canvas');tile.width=d.textureScale;tile.height=d.textureScale;tile.getContext('2d')!.drawImage(image.getElement() as HTMLImageElement,0,0,tile.width,tile.height);ctx.globalAlpha=.8;ctx.fillStyle=ctx.createPattern(tile,'repeat')!;ctx.fillRect(0,0,512,640);ctx.restore();image.dispose()}const objects=await Promise.all(d.layers.filter(l=>l.side===side).map(layerObject));canvas.clear();canvas.backgroundImage=new FabricImage(background);canvas.clipPath=d.freeCanvas?undefined:new Path(silhouettePath(d,side),{absolutePositioned:true});objects.forEach(o=>canvas.add(o));canvas.renderAll()}
export async function texture(d:Design,side:Side){const c=new StaticCanvas(undefined,{width:512,height:640,renderOnAddRemove:false});try{await paint(c,d,side);return c.toCanvasElement()}finally{await c.dispose()}}
