// Device-only storage for anonymous/manual work. Provider keys never enter this store.
let localMode=false;
export const useLocalWorkspace=(enabled=true)=>{localMode=enabled};
export const isLocalWorkspace=()=>localMode;
async function database(){return new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('urdesigner-device',1);req.onupgradeneeded=()=>{req.result.createObjectStore('assets')};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(Error('Device storage is unavailable'))})}
export async function localImage(id:string,blob?:Blob):Promise<Blob|undefined>{const db=await database();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('assets',blob?'readwrite':'readonly'),store=tx.objectStore('assets');const req=blob?store.put(blob,id):store.get(id);let value:Blob|undefined;req.onsuccess=()=>{value=blob||req.result};tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(Error('Device image storage is full'))})}finally{db.close()}}
export async function assetBlob(id:string){const local=await localImage(id);if(local)return local;const res=await fetch('/api/assets/'+id);if(!res.ok)throw Error('Image unavailable');return res.blob()}
export async function assetURL(id:string){const blob=await assetBlob(id);return new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result as string);reader.onerror=()=>reject(Error('Image unavailable'));reader.readAsDataURL(blob)})}
export function localProjects(path:string,method:string,data?:any){const key='urdesigner-local-projects',all=JSON.parse(localStorage.getItem(key)||'{}'),id=path.split('/')[1];if(path.startsWith('history/'))return all[id]?.history||[];if(method==='GET')return id?all[id]||Promise.reject(Error('Local project not found')):Object.values(all).sort((a:any,b:any)=>b.updated-a.updated);if(method==='DELETE'){delete all[id];localStorage.setItem(key,JSON.stringify(all));return{ok:true}}if(method==='PUT'){const revision=(all[id]?.revision||0)+1;if(data.revision!==(all[id]?.revision||0))throw Error('A newer device version exists. Reopen the saved project before saving');const history=all[id]?[{revision:all[id].revision,document:all[id].document,created:all[id].updated},...(all[id].history||[])].slice(0,10):[];all[id]={id,title:data.document.title,collection:data.document.collection,favorite:data.document.favorite,document:data.document,history,revision,updated:Date.now()};localStorage.setItem(key,JSON.stringify(all));return{revision}}throw Error('Unsupported local action')}
