import * as T from 'three';
import {Design,Side,dimensions} from './model';
import {constructionDefaults} from './catalog';
function radius(d:Design,y:number){const z=dimensions(d),c=d.construction||constructionDefaults;const keys=z.top===300?[[300,78],[340,94],[z.bottom,z.hem]]:[[100,101],[160,92],[214,88],[286,z.waist],[340,Math.min(z.hem,98)],[z.bottom,z.hem]];const sorted=keys.filter(p=>p[0]<=z.bottom).sort((a,b)=>a[0]-b[0]);for(let i=1;i<sorted.length;i++){if(y<=sorted[i][0]){const a=sorted[i-1],b=sorted[i],t=Math.max(0,(y-a[0])/(b[0]-a[0]||1));return a[1]+(b[1]-a[1])*t}}return z.hem}
function neckY(d:Design,side:Side,a:number){const n=(d.construction||constructionDefaults)[side==='front'?'neckline':'backNeckline'];const s=Math.abs(Math.sin(a));if(n==='off-shoulder')return 135;if(n==='boat')return 112+10*(1-s);if(s>.43)return 105;if(n==='collared')return 110+50*(1-s/.43);if(n==='v')return 105+65*(1-s/.43);if(n==='square')return 150;if(n==='sweetheart')return 132+12*Math.sin(s/.43*Math.PI);if(n==='halter')return 98+45*s;return 105+35*Math.sqrt(Math.max(0,1-(s/.43)**2))}
export function garmentSurface(d:Design,side:Side,startY?:number,endY?:number){const z=dimensions(d),c=d.construction||constructionDefaults,N=64,R=48,vertices:number[]=[],uv:number[]=[],indices:number[]=[];for(let j=0;j<=R;j++)for(let i=0;i<=N;i++){const a=-Math.PI/2+i/N*Math.PI,t=j/R;const start=startY??(z.top===300?300:neckY(d,side,a));let y=start+((endY??z.bottom)-start)*t;if(c.hem==='asymmetric')y-=35*(.5+.5*Math.sin(a))*t**6;if(c.hem==='scalloped')y-=6*(1+Math.cos(a*16))*t**8;const r=radius(d,y);const folds=(d.details?.pleats?7:z.hem>130?4:1)*Math.sin(a*(d.details?.pleats?32:20))*Math.max(0,Math.min(1,(y-285)/Math.max(1,z.bottom-285)));const x=Math.sin(a)*(r+folds);const depth=(y<290?r*.55:r*.48)+folds;const zz=Math.cos(a)*depth*(side==='front'?1:-1);vertices.push(x/180,(340-y)/180,zz/180);uv.push((256+(side==='front'?x:-x))/512,1-y/640)}for(let j=0;j<R;j++)for(let i=0;i<N;i++){const a=j*(N+1)+i,b=a+N+1;indices.push(a,b,a+1,a+1,b,b+1)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();return g}
export function sleeveSurface(d:Design,left:boolean,side:Side='front'){const c=d.construction||constructionDefaults,len=25+d.sleeve*150,N=32,R=18,v:number[]=[],uv:number[]=[],ix:number[]=[];for(let j=0;j<=R;j++)for(let i=0;i<=N;i++){const t=j/R,a=-Math.PI/2+i/N*Math.PI;let radius=25-8*t;if(c.sleeveStyle==='bell')radius+=26*t*t;if(c.sleeveStyle==='puff')radius+=19*Math.sin(t*Math.PI);if(c.sleeveStyle==='cap')radius=25-20*t;const x=(98+t*len*.38+Math.sin(a)*radius)*(left?-1:1),y=137+t*len+Math.cos(a)*radius*.3,z=Math.cos(a)*radius*(side==='front'?1:-1);v.push(x/180,(340-y)/180,z/180);uv.push((256+(side==='front'?x:-x))/512,1-y/640)}for(let j=0;j<R;j++)for(let i=0;i<N;i++){const a=j*(N+1)+i,b=a+N+1;ix.push(a,b,a+1,a+1,b,b+1)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();return g}
export function pantsSurface(d:Design,left:boolean,side:Side='front'){
const z=dimensions(d),N=32,R=44,v:number[]=[],uv:number[]=[],ix:number[]=[],hemY=Math.max(405,z.bottom),crotchY=386,sign=left?-1:1;
for(let j=0;j<=R;j++)for(let i=0;i<=N;i++){
 const y=300+j/R*(hemY-300),u=i/N,legU=2*u-1;let x:number,zz:number;
 if(y<=crotchY){const t=(y-300)/(crotchY-300),width=t<.45?(78*d.construction.waist)+(94-78*d.construction.waist)*t/.45:94+(84-94)*(t-.45)/.55;const s=left?-1+u:u;x=width*s;const whole=width*.55*Math.sqrt(Math.max(0,1-s*s)),q=2*Math.abs(s)-1,split=width*.5*.85*Math.sqrt(Math.max(0,1-q*q));const k=Math.max(0,(t-.4)/.6),blend=k*k*(3-2*k);zz=whole*(1-blend)+split*blend;
 }else{const t=(y-crotchY)/(hemY-crotchY),hemRadius=Math.max(15,(z.hem-12)/2),r=42+(hemRadius-42)*t,gap=24*t*t*(3-2*t);x=sign*(r+gap/2)+legU*r;zz=r*.85*Math.sqrt(Math.max(0,1-legU*legU));}
 v.push(x/180,(340-y)/180,zz*(side==='front'?1:-1)/180);uv.push((256+(side==='front'?x:-x))/512,1-y/640);
}
for(let j=0;j<R;j++)for(let i=0;i<N;i++){const a=j*(N+1)+i,b=a+N+1;side==='front'?ix.push(a,b,a+1,a+1,b,b+1):ix.push(a,a+1,b,a+1,b+1,b)}
const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();return g;
}
export function mannequin(){const group=new T.Group(),mat=new T.MeshStandardMaterial({color:'#d1c5b6',roughness:.77});const ellipsoid=(x:number,y:number,z:number,sx:number,sy:number,sz:number)=>{const m=new T.Mesh(new T.SphereGeometry(1,32,24),mat);m.position.set(x,y,z);m.scale.set(sx,sy,sz);group.add(m)};const points=[[.33,-.1],[.44,.22],[.4,.43],[.32,.69],[.38,.94],[.46,1.1],[.48,1.23],[.3,1.31],[.13,1.37],[.12,1.57]].map(([r,y])=>new T.Vector2(r,y));const torso=new T.Mesh(new T.LatheGeometry(points,64),mat);torso.scale.set(.95,1,.49);group.add(torso);ellipsoid(0,1.78,0,.22,.3,.2);for(const sign of [-1,1]){ellipsoid(sign*.58,.91,0,.105,.43,.105);ellipsoid(sign*.74,.36,0,.08,.35,.08);ellipsoid(sign*.8,.03,0,.075,.13,.045);ellipsoid(sign*.21,-.58,0,.16,.62,.16);ellipsoid(sign*.2,-1.22,0,.1,.3,.1)}return group}
export function drape(){const v:number[]=[],uv:number[]=[],ix:number[]=[],N=25,R=40;for(let j=0;j<=R;j++)for(let i=0;i<=N;i++){const t=j/R,u=i/N,x=.37-t*.82+(u-.5)*.38,y=1.24-t*2.3,z=.39+Math.sin(t*Math.PI)*.12+.045*Math.sin(u*15+t*4);v.push(x,y,z);uv.push(u,t)}for(let j=0;j<R;j++)for(let i=0;i<N;i++){const a=j*(N+1)+i,b=a+N+1;ix.push(a,b,a+1,a+1,b,b+1)}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.setIndex(ix);g.computeVertexNormals();return g}
