import {z} from 'zod';
export const color=z.string().regex(/^#[0-9a-f]{6}$/i);
import {garmentTypes,garmentNames,garmentSpec,necklines,sleeveStyles,constructionDefaults} from './catalog';
export {garmentTypes,garmentNames} from './catalog';
export const fabrics=['cotton','linen','satin','denim','silk','chiffon','georgette','organza','velvet','brocade','lace','jersey'] as const;
const number=z.number().finite();
export const layerSchema=z.object({id:z.string().uuid(),name:z.string().max(80),type:z.enum(['text','rect','circle','path','image']),side:z.enum(['front','back']),x:number.min(-1000).max(2000),y:number.min(-1000).max(2000),scaleX:number.min(-10).max(10),scaleY:number.min(-10).max(10),angle:number.min(-3600).max(3600),fill:color,opacity:number.min(0).max(1),visible:z.boolean(),locked:z.boolean(),width:number.min(0).max(2048),height:number.min(0).max(2048),text:z.string().max(500).optional(),fontSize:number.min(8).max(200).optional(),fontFamily:z.enum(['Arial','Georgia','Courier New']).optional(),path:z.array(z.array(z.union([number.min(-10000).max(10000),z.enum(['M','L','Q','C','Z','m','l','q','c','z'])]))).max(6000).optional(),strokeWidth:number.min(1).max(60).optional(),asset:z.string().regex(/^[0-9a-f-]{36}$/i).optional()}).strict();
export const documentSchema=z.object({schemaVersion:z.literal(1),title:z.string().min(1).max(100),garment:z.enum(garmentTypes),freeCanvas:z.boolean().default(false),fabricImage:z.string().uuid().optional(),textureScale:number.min(16).max(200).default(70),color,accent:color,fabric:z.enum(fabrics),construction:z.object({neckline:z.enum(necklines),backNeckline:z.enum(necklines),sleeveStyle:z.enum(sleeveStyles),length:number.min(.55).max(1.08),flare:number.min(.55).max(1.22),waist:number.min(.8).max(1.3),hem:z.enum(['straight','asymmetric','scalloped']),closure:z.enum(['none','buttons','zipper','wrap']),trim:z.enum(['none','border','lace','embroidered']),dupatta:z.boolean()}).strict().default(constructionDefaults),pattern:z.enum(['solid','pinstripe','check','dots','floral','paisley','chevron']),sleeve:number.min(0).max(1),pocket:z.boolean(),layers:z.array(layerSchema).max(80),notes:z.string().max(4000),measurements:z.object({chest:number.min(0).max(250),waist:number.min(0).max(250),length:number.min(0).max(250)}).strict()}).strict();
export type Design=z.infer<typeof documentSchema>;export type Layer=z.infer<typeof layerSchema>;
export type Side='front'|'back';
export function freshDesign():Design{return {schemaVersion:1,title:'My A-line collection',garment:'dress',freeCanvas:false,textureScale:70,color:'#c3b8a5',accent:'#6e3f4e',fabric:'cotton',construction:{...constructionDefaults},pattern:'solid',sleeve:.25,pocket:false,layers:[],notes:'',measurements:{chest:0,waist:0,length:0}}}
export function baseLayer(type:Layer['type'],side:Side):Layer{return{id:crypto.randomUUID(),name:type==='text'?'Your signature':type==='path'?'Brush stroke':'New '+type,type,side,x:206,y:250,scaleX:1,scaleY:1,angle:0,fill:'#59364a',opacity:1,visible:true,locked:false,width:100,height:100,...(type==='text'?{text:'UR\nDESIGNER',fontSize:26,fontFamily:'Georgia' as const}:{} )}}
export const proposalSchema=z.object({explanation:z.string().max(4000),changes:z.object({color:color.optional(),accent:color.optional(),fabric:z.enum(fabrics).optional(),pattern:z.enum(['solid','pinstripe','check','dots','floral','paisley','chevron']).optional(),pocket:z.boolean().optional()}).strict()}).strict();
export type Proposal=z.infer<typeof proposalSchema>;
export function applyProposal(doc:Design,proposal:unknown):Design{const p=proposalSchema.parse(proposal);return documentSchema.parse({...doc,...p.changes})}
export function normalizeDocument(value:unknown):Design{return documentSchema.parse(value)}
export function selectGarment(d:Design,id:Design['garment']):Design{const spec=garmentSpec(id);return {...d,garment:id,sleeve:spec.sleeve,construction:{...constructionDefaults,neckline:spec.neck as Design['construction']['neckline'],sleeveStyle:spec.sleeve===0?'sleeveless':'straight',closure:id==='wrap'?'wrap':['blazer','shirt_dress'].includes(id)?'buttons':'none'}}}
export function dimensions(d:Design){const s=garmentSpec(d.garment),c=d.construction||constructionDefaults;return{top:['skirt','pants'].includes(s.kind)?300:100,bottom:Math.min(620,100+(s.bottom-100)*c.length),hem:Math.min(228,s.width*c.flare),waist:74*c.waist,kind:s.kind}}
export function neckPoints(d:Design,side:Side='front'):[number,number][]{const neck=(d.construction||constructionDefaults)[side==='front'?'neckline':'backNeckline'];if(neck==='v')return [[296,102],[256,180],[216,102]];if(neck==='square')return [[296,102],[296,156],[216,156],[216,102]];if(neck==='boat'||neck==='off-shoulder')return [[330,115],[300,134],[256,140],[212,134],[182,115]];if(neck==='halter')return [[278,98],[256,108],[234,98]];const pts:[number,number][]=[];for(let i=0;i<=24;i++){const t=i/24*Math.PI;pts.push([256+40*Math.cos(t),102+(neck==='sweetheart'?35+14*Math.cos(t*2):35)*Math.sin(t)])}return pts}
export function contour(d:Design,side:Side='front'):[number,number][]{const z=dimensions(d),c=d.construction||constructionDefaults;if(z.kind==='skirt')return [[178,300],[334,300],[256+z.hem,z.bottom],[256-z.hem,z.bottom]];if(z.kind==='pants'){const w=z.hem;return [[174,300],[338,300],[256+w,z.bottom],[272,z.bottom],[256,386],[240,z.bottom],[256-w,z.bottom]]}
const sleeve=c.sleeveStyle==='sleeveless'?0:15+d.sleeve*95;const bell=c.sleeveStyle==='bell'?25:0;const waist=z.waist;const pts:[number,number][]=[[216,102],[176,112],[156-sleeve*.65,150],[157-sleeve,182+sleeve*1.8],[183+bell-sleeve*.35,190+sleeve*1.6],[174,199],[256-waist,286],[256-z.hem,z.bottom]];
if(z.kind==='jumpsuit'){pts.push([240,z.bottom],[256,379],[272,z.bottom])}if(c.hem==='asymmetric')pts.push([256,z.bottom-45]);if(c.hem==='scalloped')for(let i=1;i<16;i++)pts.push([256-z.hem+2*z.hem*i/16,z.bottom-8+8*Math.sin(i*Math.PI/2)]);
pts.push([256+z.hem,z.bottom],[256+waist,286],[338,199],[329-bell+sleeve*.35,190+sleeve*1.6],[355+sleeve,182+sleeve*1.8],[356+sleeve*.65,150],[336,112],...neckPoints(d,side));return pts}
export function silhouettePath(d:Design,side:Side='front'):string{const p=contour(d,side);return 'M '+p.map(p=>p.join(' ')).join(' L ')+' Z'}
export function drawGarment(ctx:CanvasRenderingContext2D,d:Design,side:Side='front'){ctx.save();ctx.clearRect(0,0,512,640);const z=dimensions(d),c=d.construction||constructionDefaults;const path=new Path2D(silhouettePath(d,side));ctx.clip(path);ctx.fillStyle=d.color;ctx.fillRect(0,0,512,640);ctx.strokeStyle=d.accent;ctx.fillStyle=d.accent;ctx.globalAlpha=.5;
if(d.pattern==='pinstripe')for(let x=0;x<512;x+=17){ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,640);ctx.stroke()}
if(d.pattern==='check')for(let x=0;x<640;x+=27){ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,640);ctx.moveTo(0,x);ctx.lineTo(512,x);ctx.stroke()}
if(d.pattern==='dots')for(let y=0;y<640;y+=24)for(let x=0;x<512;x+=24){ctx.beginPath();ctx.arc(x+(y%48?12:0),y,2,0,Math.PI*2);ctx.fill()}
if(d.pattern==='chevron')for(let y=0;y<640;y+=24){ctx.beginPath();for(let x=0;x<=512;x+=16)ctx.lineTo(x,y+(x%32?12:0));ctx.stroke()}
if(d.pattern==='floral'||d.pattern==='paisley')for(let y=110;y<640;y+=45)for(let x=40;x<512;x+=42){ctx.beginPath();if(d.pattern==='floral'){for(let a=0;a<6;a++){const t=a*Math.PI/3;ctx.moveTo(x+Math.cos(t)*8+4,y+Math.sin(t)*8);ctx.ellipse(x+Math.cos(t)*8,y+Math.sin(t)*8,4,7,t,0,Math.PI*2)}}else{ctx.ellipse(x,y,7,12,.5,0,Math.PI*2);ctx.moveTo(x,y-12);ctx.quadraticCurveTo(x+22,y-22,x+14,y)}ctx.stroke()}
ctx.globalAlpha=.055;ctx.fillStyle='#000000';for(let y=0;y<640;y+=d.fabric==='linen'?3:2)ctx.fillRect(0,y,512,1);ctx.globalAlpha=.6;ctx.strokeStyle=d.accent;ctx.lineWidth=1.5;ctx.stroke(path);
if(c.trim!=='none'){ctx.lineWidth=c.trim==='border'?12:3;ctx.beginPath();ctx.moveTo(20,z.bottom-15);ctx.lineTo(492,z.bottom-15);ctx.stroke();if(c.trim==='lace'||c.trim==='embroidered')for(let x=0;x<512;x+=12){ctx.beginPath();ctx.arc(x,z.bottom-22,7,0,Math.PI*2);ctx.stroke()}}
if(side==='front'&&c.closure==='buttons'){for(let y=176;y<Math.min(z.bottom-20,390);y+=25){ctx.beginPath();ctx.arc(256,y,3,0,Math.PI*2);ctx.fill()}}
if(c.closure==='zipper'){ctx.setLineDash([3,2]);ctx.beginPath();ctx.moveTo(256,175);ctx.lineTo(256,Math.min(z.bottom-20,390));ctx.stroke();ctx.setLineDash([])}
if(c.closure==='wrap'){ctx.beginPath();ctx.moveTo(296,112);ctx.lineTo(210,300);ctx.lineTo(280,z.bottom);ctx.stroke()}
if(d.pocket&&side==='front')ctx.strokeRect(290,215,37,45);if(d.garment==='saree'&&side==='front'){ctx.globalAlpha=.5;ctx.lineWidth=62;ctx.beginPath();ctx.moveTo(326,118);ctx.bezierCurveTo(300,235,208,255,190,350);ctx.stroke()}
if(['lehenga','coord'].includes(d.garment)){ctx.clearRect(155,300,205,17);ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(150,321);ctx.lineTo(370,321);ctx.stroke()}
ctx.restore();}
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
