'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {Design,contour,Side} from '@/lib/urdesigner/model';
import {texture} from '@/lib/urdesigner/canvas';
import {garmentSurface,sleeveSurface,pantsSurface,mannequin,drape} from '@/lib/urdesigner/mesh';
import {garmentSpec} from '@/lib/urdesigner/catalog';
export default function GarmentView({design,onSide,light,exportRef}:{design:Design;onSide:(s:Side)=>void;light:number;exportRef:React.RefObject<(()=>void)|null>}){
 const host=useRef<HTMLDivElement>(null),state=useRef<any>(null),[failed,setFailed]=useState(false),latestSide=useRef(onSide);latestSide.current=onSide;
 useEffect(()=>{let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;host.current!.appendChild(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,100);camera.position.set(1.5,.4,7.4);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=3;controls.maxDistance=8;controls.target.set(0,.12,0);const ambient=new T.HemisphereLight(0xfff3df,0x484963,2);scene.add(ambient);const key=new T.DirectionalLight(0xfff4e5,3);key.position.set(-3,5,4);scene.add(key);const rim=new T.DirectionalLight(0xdbe8ff,2);rim.position.set(3,1,-4);scene.add(rim);const group=new T.Group();scene.add(group);const avatar=mannequin();scene.add(avatar);const floor=new T.Mesh(new T.CylinderGeometry(.8,.87,.07,64),new T.MeshStandardMaterial({color:0x303033,roughness:.7}));floor.position.y=-1.57;scene.add(floor);const resize=new ResizeObserver(()=>{const w=host.current?.clientWidth||400,h=host.current?.clientHeight||600;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(host.current!);const ray=new T.Raycaster();const pick=(e:MouseEvent)=>{const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children)[0];if(hit)latestSide.current(hit.object.userData.side||'front')};renderer.domElement.addEventListener('dblclick',pick);let frame=0;function animate(){frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();state.current={renderer,scene,camera,controls,group,key,avatar};exportRef.current=()=>renderer.domElement.toBlob(b=>{if(b){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='urdesigner-3d.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}});return()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();group.traverse((o:any)=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose()});renderer.dispose();renderer.domElement.remove();state.current=null;exportRef.current=null}},[]);
 useEffect(()=>{const s=state.current;if(!s)return;let alive=true;Promise.all([texture(design,'front'),texture(design,'back')]).then(images=>{if(!alive)return;for(const o of [...s.group.children]){s.group.remove(o);o.geometry.dispose();o.material.map?.dispose();o.material.dispose()}const spec=garmentSpec(design.garment);const materials=images.map(image=>{const map=new T.CanvasTexture(image);map.colorSpace=T.SRGBColorSpace;map.anisotropy=8;return new T.MeshPhysicalMaterial({map,roughness:['satin','silk'].includes(design.fabric)?.27:design.fabric==='velvet'?1:.78,metalness:design.fabric==='brocade'?.22:0,side:T.DoubleSide,transparent:true,alphaTest:.08,clearcoat:['silk','satin'].includes(design.fabric)?.3:0})});
const add=(geometry:T.BufferGeometry,material:T.Material,side='front')=>{const mesh=new T.Mesh(geometry,material);mesh.userData.side=side;s.group.add(mesh)};
if(spec.kind==='pants'){for(const left of [false,true])add(pantsSurface(design,left),materials[0].clone())}else if(spec.kind==='jumpsuit'){const top={...design,garment:'top' as const,construction:{...design.construction,length:.94}};add(garmentSurface(top,'front'),materials[0]);add(garmentSurface(top,'back'),materials[1]);for(const left of [false,true])add(pantsSurface(design,left),new T.MeshStandardMaterial({color:design.color,roughness:.65,side:T.DoubleSide}))}else{add(garmentSurface(design,'front'),materials[0]);add(garmentSurface(design,'back'),materials[1])}
if(!['pants','skirt'].includes(spec.kind)&&design.construction.sleeveStyle!=='sleeveless'&&design.sleeve>0){for(const left of [false,true])add(sleeveSurface(design,left),new T.MeshPhysicalMaterial({color:design.color,roughness:design.fabric==='satin'?.3:.75,side:T.DoubleSide}))}
if(design.garment==='saree'||design.construction.dupatta)add(drape(),new T.MeshPhysicalMaterial({color:design.accent,roughness:.4,side:T.DoubleSide,transparent:true,opacity:.92}));
}).catch(()=>setFailed(true));return()=>{alive=false}},[design]);
 useEffect(()=>{if(state.current)state.current.key.intensity=light},[light]);
 return <><div ref={host} className="three-host" aria-label="Interactive 3D garment. Drag to rotate, scroll to zoom, double-click to select front or back."/>{failed&&<p className="webgl-fallback">3D preview is unavailable on this device. Your 2D design remains editable.</p>}<div className="orbit-controls"><button onClick={()=>{const s=state.current;if(s){s.camera.position.set(0,.4,7.4);s.controls.target.set(0,.12,0)}}}>Reset view</button><button onClick={()=>{if(state.current)state.current.avatar.visible=!state.current.avatar.visible}}>Show / hide mannequin</button><span>Drag to rotate · Scroll to zoom</span></div></>
}
