'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {RoomEnvironment} from 'three/examples/jsm/environments/RoomEnvironment.js';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {Design,Side,downloadBlob,drawGarment} from '@/lib/urdesigner/model';
import {buildGarment,disposeGroup} from '@/lib/urdesigner/garment-scene';
import {mannequin} from '@/lib/urdesigner/mesh';
function FlatFallback({design}:{design:Design}){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const ctx=ref.current?.getContext('2d');if(ctx)drawGarment(ctx,design,'back')},[design]);return <div className="flat-fallback"><canvas ref={ref} width={512} height={640} aria-label="Back design fallback"/><p>Back view · 3D acceleration unavailable on this device</p></div>}
export default function GarmentView({design,onSide,onPart,light,exportRef,glbRef}:{design:Design;onSide:(s:Side)=>void;onPart?:(part:string)=>void;light:number;exportRef:React.RefObject<(()=>void)|null>;glbRef?:React.RefObject<(()=>Promise<void>)|null>}){
 const renderKey=JSON.stringify({...design,title:'',notes:'',measurements:{},references:[],collection:'',favorite:false});
 const host=useRef<HTMLDivElement>(null),state=useRef<any>(null),[failed,setFailed]=useState(false),[loading,setLoading]=useState(true),latest=useRef({onSide,onPart});latest.current={onSide,onPart};
 useEffect(()=>{let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.current!.appendChild(renderer.domElement);const scene=new T.Scene();const environment=new RoomEnvironment();const pmrem=new T.PMREMGenerator(renderer);const envMap=pmrem.fromScene(environment,.04);scene.environment=envMap.texture;scene.environmentIntensity=.55;environment.dispose();pmrem.dispose();const camera=new T.PerspectiveCamera(34,1,.1,100);camera.position.set(1.5,.4,7.4);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=1.2;controls.maxDistance=10;controls.target.set(0,.12,0);scene.add(new T.HemisphereLight(0xfff3df,0x484963,2));const key=new T.DirectionalLight(0xfff4e5,light);key.position.set(-3,5,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-3;key.shadow.camera.right=3;key.shadow.camera.top=3;key.shadow.camera.bottom=-3;key.shadow.normalBias=.03;key.shadow.bias=-.0002;scene.add(key);const rim=new T.DirectionalLight(0xdbe8ff,2);rim.position.set(3,1,-4);scene.add(rim);const group=new T.Group();scene.add(group);const avatar=mannequin();scene.add(avatar);const floor=new T.Mesh(new T.CylinderGeometry(.8,.87,.07,64),new T.MeshStandardMaterial({color:0x303033,roughness:.7}));floor.receiveShadow=true;floor.position.y=-1.57;scene.add(floor);const resize=new ResizeObserver(()=>{const w=host.current?.clientWidth||400,h=host.current?.clientHeight||600;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(host.current!);const ray=new T.Raycaster();const pick=(e:MouseEvent)=>{const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children,true)[0];if(hit){latest.current.onSide(hit.object.userData.side||'front');const part=hit.object.userData.part;latest.current.onPart?.(part==='bodice'&&hit.point.y<.22?'bottom':part||'bodice')}};renderer.domElement.addEventListener('dblclick',pick);let frame=0;function animate(){frame=requestAnimationFrame(animate);if(host.current?.offsetParent!==null){controls.update();renderer.render(scene,camera)}}animate();state.current={renderer,scene,camera,controls,group,key,rim,avatar};exportRef.current=()=>{renderer.render(scene,camera);renderer.domElement.toBlob(b=>b&&downloadBlob(b,'urdesigner-3d.png'))};return()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();disposeGroup(scene);envMap.dispose();renderer.dispose();renderer.domElement.remove();state.current=null;exportRef.current=null;if(glbRef)glbRef.current=null}},[]);
 useEffect(()=>{const s=state.current;if(!s)return;let alive=true;setLoading(true);const timer=setTimeout(()=>{buildGarment(design).then(group=>{if(!alive){disposeGroup(group);return}disposeGroup(s.group);s.group.clear();s.group.add(group);setFailed(false);setLoading(false);if(glbRef)glbRef.current=async()=>{const {GLTFExporter}=await import('three/examples/jsm/exporters/GLTFExporter.js');const result=await new GLTFExporter().parseAsync(group,{binary:true});downloadBlob(new Blob([result as ArrayBuffer],{type:'model/gltf-binary'}),design.title+'.glb')}}).catch(()=>{if(alive){setFailed(true);setLoading(false)}})},120);return()=>{alive=false;clearTimeout(timer);if(glbRef)glbRef.current=null}},[renderKey]);
 useEffect(()=>{if(state.current)state.current.key.intensity=light},[light]);
 function cameraView(angle:number){const s=state.current;if(s){s.camera.position.set(Math.sin(angle)*6,.4,Math.cos(angle)*6);s.controls.target.set(0,.12,0);s.controls.update()}}
 return <><div ref={host} className="three-host" aria-label="Interactive 3D garment. Drag to rotate, scroll to zoom, double-click a part to edit."/>{failed?<FlatFallback design={design}/>:loading&&<span className="render-status" role="status">Updating preview…</span>}<div className="orbit-controls" style={{display:failed?'none':undefined}}><div className="camera-buttons"><button onClick={()=>cameraView(0)}>Front</button><button onClick={()=>cameraView(Math.PI)}>Back</button><button onClick={()=>cameraView(Math.PI/2)}>Side</button><button onClick={()=>{const s=state.current;if(s){s.camera.position.set(1.5,.4,7.4);s.controls.target.set(0,.12,0)}}}>Reset</button></div><div className="camera-buttons"><button onClick={()=>{if(state.current)state.current.avatar.visible=!state.current.avatar.visible}}>Mannequin</button><button onClick={()=>{if(state.current)state.current.controls.autoRotate=!state.current.controls.autoRotate}}>Turntable</button><button onClick={()=>{const s=state.current;if(s){const warm=s.key.color.getHex()!==0xffffff;s.key.color.set(warm?0xffffff:0xffe0b2);s.scene.environmentIntensity=warm?.8:.45}}}>Day / evening light</button></div><span>Drag to rotate · Double-click a part to edit</span></div></>
}
