'use client';
import {useEffect,useRef,useState} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/examples/jsm/controls/OrbitControls.js';
import {Design,contour,Side} from '@/lib/urdesigner/model';
import {texture} from '@/lib/urdesigner/canvas';
function geometry(d:Design,back=false){const pts=contour(d).map(([x,y])=>new T.Vector2((x-256)/180,(340-y)/180));const shape=new T.Shape(pts);const source=new T.ShapeGeometry(shape);const vertices:number[]=[],uv:number[]=[];const pos=source.getAttribute('position'),indices=source.index!;
 function tri(a:T.Vector2,b:T.Vector2,c:T.Vector2,n:number){if(n){const ab=a.clone().add(b).multiplyScalar(.5),bc=b.clone().add(c).multiplyScalar(.5),ca=c.clone().add(a).multiplyScalar(.5);tri(a,ab,ca,n-1);tri(ab,b,bc,n-1);tri(ca,bc,c,n-1);tri(ab,bc,ca,n-1);return}for(const p of back?[c,b,a]:[a,b,c]){const curve=Math.sqrt(Math.max(0,1-Math.pow(p.x/.9,2)))*.19;const z=(.035+curve+.014*Math.sin(p.y*12+p.x*4))*(back?-1:1);vertices.push(p.x,p.y,z);uv.push((p.x*180+256)/512,1-(340-p.y*180)/640)}}
 for(let i=0;i<indices.count;i+=3){const point=(j:number)=>new T.Vector2(pos.getX(indices.getX(j)),pos.getY(indices.getX(j)));tri(point(i),point(i+1),point(i+2),3)}source.dispose();const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(vertices,3));g.setAttribute('uv',new T.Float32BufferAttribute(uv,2));g.computeVertexNormals();return g;
}
export default function GarmentView({design,onSide,light,exportRef}:{design:Design;onSide:(s:Side)=>void;light:number;exportRef:React.RefObject<(()=>void)|null>}){
 const host=useRef<HTMLDivElement>(null),state=useRef<any>(null),[failed,setFailed]=useState(false),latestSide=useRef(onSide);latestSide.current=onSide;
 useEffect(()=>{let renderer:T.WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true})}catch{setFailed(true);return}renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;host.current!.appendChild(renderer.domElement);const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,100);camera.position.set(1.2,.15,5.3);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=2;controls.maxDistance=8;controls.target.set(0,0,0);const ambient=new T.HemisphereLight(0xfff3df,0x484963,2);scene.add(ambient);const key=new T.DirectionalLight(0xfff4e5,3);key.position.set(-3,5,4);scene.add(key);const rim=new T.DirectionalLight(0xdbe8ff,2);rim.position.set(3,1,-4);scene.add(rim);const group=new T.Group();scene.add(group);const resize=new ResizeObserver(()=>{const w=host.current?.clientWidth||400,h=host.current?.clientHeight||600;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()});resize.observe(host.current!);const ray=new T.Raycaster();const pick=(e:MouseEvent)=>{const r=renderer.domElement.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObjects(group.children)[0];if(hit)latestSide.current(hit.object.userData.side||'front')};renderer.domElement.addEventListener('dblclick',pick);let frame=0;function animate(){frame=requestAnimationFrame(animate);controls.update();renderer.render(scene,camera)}animate();state.current={renderer,scene,camera,controls,group,key};exportRef.current=()=>renderer.domElement.toBlob(b=>{if(b){const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='urdesigner-3d.png';a.click();setTimeout(()=>URL.revokeObjectURL(u),3000)}});return()=>{cancelAnimationFrame(frame);resize.disconnect();controls.dispose();group.traverse((o:any)=>{o.geometry?.dispose();o.material?.map?.dispose();o.material?.dispose()});renderer.dispose();renderer.domElement.remove();state.current=null;exportRef.current=null}},[]);
 useEffect(()=>{const s=state.current;if(!s)return;let alive=true;Promise.all([texture(design,'front'),texture(design,'back')]).then(images=>{if(!alive)return;for(const o of [...s.group.children]){s.group.remove(o);o.geometry.dispose();o.material.map?.dispose();o.material.dispose()}images.forEach((image,i)=>{const map=new T.CanvasTexture(image);map.colorSpace=T.SRGBColorSpace;map.anisotropy=8;const material=new T.MeshStandardMaterial({map,roughness:design.fabric==='satin'?.3:.9,metalness:design.fabric==='satin'?.12:0,side:T.DoubleSide,transparent:true,alphaTest:.5});const mesh=new T.Mesh(geometry(design,!!i),material);mesh.userData.side=i?'back':'front';s.group.add(mesh)});const pts=contour(design),v:number[]=[];for(let i=0;i<pts.length;i++){const a=pts[i],b=pts[(i+1)%pts.length];const point=(p:number[],back:boolean)=>{const x=(p[0]-256)/180,y=(340-p[1])/180,z=(.035+Math.sqrt(Math.max(0,1-Math.pow(x/.9,2)))*.19+.014*Math.sin(y*12+x*4))*(back?-1:1);return[x,y,z]};v.push(...point(a,false),...point(b,false),...point(a,true),...point(b,false),...point(b,true),...point(a,true))}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.computeVertexNormals();s.group.add(new T.Mesh(g,new T.MeshStandardMaterial({color:design.color,side:T.DoubleSide,roughness:.8})));}).catch(()=>setFailed(true));return()=>{alive=false}},[design]);
 useEffect(()=>{if(state.current)state.current.key.intensity=light},[light]);
 return <><div ref={host} className="three-host" aria-label="Interactive 3D garment. Drag to rotate, scroll to zoom, double-click to select front or back."/>{failed&&<p className="webgl-fallback">3D preview is unavailable on this device. Your 2D design remains editable.</p>}<div className="orbit-controls"><button onClick={()=>{const s=state.current;if(s){s.camera.position.set(0,.1,5.3);s.controls.target.set(0,0,0)}}}>Reset view</button><span>Drag to rotate · Scroll to zoom</span></div></>
}
